CREATE DATABASE IF NOT EXISTS DSTACK_ESTOQUE;

USE DSTACK_ESTOQUE;

CREATE TABLE IF NOT EXISTS USUARIOS(
COD_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(50) NOT NULL,
NOME_COMPLETO VARCHAR(70) NOT NULL,
SENHA VARCHAR(60) NOT NULL,
EMAIL VARCHAR(70) NULL,
SITUACAO ENUM('Ativo', 'Inativo'),
PERFIL ENUM('Administrador', 'Vendedor'));

INSERT INTO USUARIOS VALUES(1, 'admin', 'Administrador', '$2a$11$llP9G6IyibUob8h5XRt9xu8OruiXqodwboG6J51fMr9BwLhXmvMNS', 'sem@email', 'Ativo', 'Administrador');

CREATE TABLE IF NOT EXISTS FORNECEDORES(
COD_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CNPJ BIGINT(14) ZEROFILL UNIQUE NOT NULL,
INSCRICAO_ESTADUAL BIGINT(13) ZEROFILL NOT NULL,
TELEFONE BIGINT(10) NOT NULL,
CELULAR BIGINT(11) NULL,
FAX BIGINT(11) NULL,
CEP INT(8) ZEROFILL NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
NUMERO INT(10) NOT NULL,
BAIRRO VARCHAR(60) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
UF CHAR(2) NOT NULL,
EMAIL VARCHAR(80) NULL,
CONTATO VARCHAR(100) NULL,
OBSERVACOES VARCHAR(800) NULL,
DATA VARCHAR(10));

CREATE TABLE IF NOT EXISTS CLIENTES(
COD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME_COMPLETO VARCHAR(100) NOT NULL,
CPF BIGINT(11) ZEROFILL UNIQUE NOT NULL,
RG BIGINT(8) ZEROFILL UNIQUE NOT NULL,
FANTASIA VARCHAR(100) NULL,
PESSOA ENUM('Fisica', 'Juridica') NOT NULL,
SEXO ENUM('Masculino', 'Feminino') NOT NULL,
DATA_CADASTRO VARCHAR(10) NULL,
EMAIL VARCHAR(100) NOT NULL,
DATA_NASCIMENTO VARCHAR(10) NULL,
CEP INT(8) ZEROFILL NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
NUMERO SMALLINT NOT NULL,
BAIRRO VARCHAR(60) NOT NULL,
CIDADE VARCHAR(60) NOT NULL,
UF CHAR(2) NOT NULL,
TELEFONE BIGINT(10) NOT NULL,
FAX BIGINT(11) NULL,
BANCO VARCHAR(60) NULL,
AGENCIA CHAR(4) NULL); 

CREATE TABLE IF NOT EXISTS CATEGORIAS(
COD_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(150) NOT NULL);

CREATE TABLE IF NOT EXISTS MARCAS(
COD_MARCA INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(150) NOT NULL);

CREATE TABLE IF NOT EXISTS PRODUTOS(
COD_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
COD_FORNECEDOR INT NULL,
DESCRICAO VARCHAR(200) NOT NULL,
IMAGEM MEDIUMBLOB NULL,
UNIDADE_MEDIDA VARCHAR(4) NOT NULL,
ESTOQUE_ATUAL INT NOT NULL,
PRECO DECIMAL(19,2) NULL,
ESTOQUE_MINIMO INT NULL,
ESTOQUE_MAXIMO INT NULL,
OBSERVACOES VARCHAR(250) NULL,
COD_CATEGORIA INT NOT NULL,
COD_MARCA INT NOT NULL,
DATA DATE,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(COD_FORNECEDOR) REFERENCES FORNECEDORES(COD_FORNECEDOR),
CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA),
CONSTRAINT FK_PRODUTO_MARCA FOREIGN KEY(COD_MARCA) REFERENCES MARCAS(COD_MARCA));

CREATE TABLE IF NOT EXISTS ESTADO (
ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(75) DEFAULT NULL,
UF VARCHAR(5) DEFAULT NULL) AUTO_INCREMENT=28;

INSERT INTO ESTADO (ID, NOME, UF) VALUES(1, 'Acre', 'AC'),(2, 'Alagoas', 'AL'),(3, 'Amazonas', 'AM'),(4, 'Amapá', 'AP'),(5, 'Bahia', 'BA'),(6, 'Ceará', 'CE'),(7, 'Distrito Federal', 'DF'),(8, 'Espírito Santo', 'ES'),(9, 'Goiás', 'GO'),(10, 'Maranhão', 'MA'),(11, 'Minas Gerais', 'MG'),(12, 'Mato Grosso do Sul', 'MS'),(13, 'Mato Grosso', 'MT'),(14, 'Pará', 'PA'),(15, 'Paraíba', 'PB'),(16, 'Pernambuco', 'PE'),(17, 'Piauí', 'PI'),(18, 'Paraná', 'PR'),(19, 'Rio de Janeiro', 'RJ'),(20, 'Rio Grande do Norte', 'RN'),(21, 'Rondônia', 'RO'),(22, 'Roraima', 'RR'),(23, 'Rio Grande do Sul', 'RS'),(24, 'Santa Catarina', 'SC'),(25, 'Sergipe', 'SE'),(26, 'São Paulo', 'SP'),(27, 'Tocantins', 'TO');